# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "user.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\nuser.proto\x12\x0cuser_service"0\n\x11UserCreateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t"/\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t"!\n\x0eGetUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t"\x12\n\x10ListUsersRequest"6\n\x11ListUsersResponse\x12!\n\x05users\x18\x01 \x03(\x0b\x32\x12.user_service.User"$\n\x11UserExistsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t"$\n\x12UserExistsResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x32\xb4\x02\n\x0bUserService\x12\x43\n\nCreateUser\x12\x1f.user_service.UserCreateRequest\x1a\x12.user_service.User"\x00\x12=\n\x07GetUser\x12\x1c.user_service.GetUserRequest\x1a\x12.user_service.User"\x00\x12N\n\tListUsers\x12\x1e.user_service.ListUsersRequest\x1a\x1f.user_service.ListUsersResponse"\x00\x12Q\n\nUserExists\x12\x1f.user_service.UserExistsRequest\x1a .user_service.UserExistsResponse"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "user_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_USERCREATEREQUEST"]._serialized_start = 28
    _globals["_USERCREATEREQUEST"]._serialized_end = 76
    _globals["_USER"]._serialized_start = 78
    _globals["_USER"]._serialized_end = 125
    _globals["_GETUSERREQUEST"]._serialized_start = 127
    _globals["_GETUSERREQUEST"]._serialized_end = 160
    _globals["_LISTUSERSREQUEST"]._serialized_start = 162
    _globals["_LISTUSERSREQUEST"]._serialized_end = 180
    _globals["_LISTUSERSRESPONSE"]._serialized_start = 182
    _globals["_LISTUSERSRESPONSE"]._serialized_end = 236
    _globals["_USEREXISTSREQUEST"]._serialized_start = 238
    _globals["_USEREXISTSREQUEST"]._serialized_end = 274
    _globals["_USEREXISTSRESPONSE"]._serialized_start = 276
    _globals["_USEREXISTSRESPONSE"]._serialized_end = 312
    _globals["_USERSERVICE"]._serialized_start = 315
    _globals["_USERSERVICE"]._serialized_end = 623
# @@protoc_insertion_point(module_scope)
