# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: product.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "product.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rproduct.proto\x12\x0fproduct_service"U\n\x14ProductCreateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\x12\x14\n\x07user_id\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_user_id"T\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\x12\x14\n\x07user_id\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_user_id"\'\n\x11GetProductRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t"\x15\n\x13ListProductsRequest"B\n\x14ListProductsResponse\x12*\n\x08products\x18\x01 \x03(\x0b\x32\x18.product_service.Product2\x91\x02\n\x0eProductService\x12R\n\rCreateProduct\x12%.product_service.ProductCreateRequest\x1a\x18.product_service.Product"\x00\x12L\n\nGetProduct\x12".product_service.GetProductRequest\x1a\x18.product_service.Product"\x00\x12]\n\x0cListProducts\x12$.product_service.ListProductsRequest\x1a%.product_service.ListProductsResponse"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "product_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_PRODUCTCREATEREQUEST"]._serialized_start = 34
    _globals["_PRODUCTCREATEREQUEST"]._serialized_end = 119
    _globals["_PRODUCT"]._serialized_start = 121
    _globals["_PRODUCT"]._serialized_end = 205
    _globals["_GETPRODUCTREQUEST"]._serialized_start = 207
    _globals["_GETPRODUCTREQUEST"]._serialized_end = 246
    _globals["_LISTPRODUCTSREQUEST"]._serialized_start = 248
    _globals["_LISTPRODUCTSREQUEST"]._serialized_end = 269
    _globals["_LISTPRODUCTSRESPONSE"]._serialized_start = 271
    _globals["_LISTPRODUCTSRESPONSE"]._serialized_end = 337
    _globals["_PRODUCTSERVICE"]._serialized_start = 340
    _globals["_PRODUCTSERVICE"]._serialized_end = 613
# @@protoc_insertion_point(module_scope)
